#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "json"
require "optparse"
require "pathname"
require_relative "palma_metadata"

options = {
  root: File.expand_path("..", __dir__),
  output_dir: nil,
  check: false
}

OptionParser.new do |parser|
  parser.banner = "Usage: generate_repository_index.rb [--root PATH] [--output-dir PATH] [--check]"
  parser.on("--root PATH", "Palma-method root") { |value| options[:root] = value }
  parser.on("--output-dir PATH", "Generated-output directory") { |value| options[:output_dir] = value }
  parser.on("--check", "Compare generated bytes without writing") { options[:check] = true }
end.parse!

root = Pathname.new(options[:root]).expand_path
output_dir = Pathname.new(options[:output_dir] || root.join("generated")).expand_path
result = PalmaKnowledgeOS::Scanner.new(root).scan
builder = PalmaKnowledgeOS::IndexBuilder.new(result)
index = builder.build
expected = {
  output_dir.join("repository-index.json") => JSON.pretty_generate(index) + "\n",
  output_dir.join("repository-index.md") => builder.render_markdown(index)
}

if options[:check]
  mismatches = expected.each_with_object([]) do |(path, content), items|
    items << path.basename.to_s unless path.file? && path.read(encoding: "UTF-8") == content
  end.sort

  if mismatches.empty?
    puts "repository index is deterministic and up to date"
    exit 0
  end

  mismatches.each { |name| warn "out of date: #{name}" }
  exit 1
end

FileUtils.mkdir_p(output_dir)
expected.each { |path, content| path.write(content, mode: "w", encoding: "UTF-8") }
puts "wrote #{expected.keys.map { |path| path.relative_path_from(root) }.sort.join(', ')}"
exit(result.error_count.zero? ? 0 : 1)
